### ISSUE TITLE
Initial Setup Instruction Error

### ISSUE THREAD

**Issue by vladimirfomene** [openMF/mobile-money-module#17]
**Summary:**
I had the following error whilst I was trying to setup my local environment. When I type the command "git add remote upstream https://github.com/openMF/mobile-money-module" I get the following error:
fatal: pathspec 'remote' did not match any files

**Steps to reproduce:**
Following the initial setup instruction in the readme of the repository.
**Expected behavior:**
No error

**Observed behavior:**
I saw the following error: fatal: pathspec 'remote' did not match any files

**Device and Android version:**
Terminal on a linux machine.
Lenovo E531

**Screenshots:**

![screenshot from 2017-05-09 11-45-44](https://cloud.githubusercontent.com/assets/11140070/25849231/33a421aa-34ad-11e7-98f0-a17cc67a7be6.png)

**Comment by awasum** [comment]
git remote add upstream url.

**Comment by awasum** [comment]
fixed by https://github.com/openMF/mobile-money-module/pull/18
