### ISSUE TITLE
Generic Design

### ISSUE THREAD

**Issue by awasum** [openMF/mobile-money-module#7]
Mifos/Fineract supports multitenancy. To account for this and the fact that each tenant may support many Mobile Money providers and also a single provider will serve different tenants(MFIs), I propose the following data model for handling this functionality.
![mobile money database v3 17-02-25 14 04 02](https://cloud.githubusercontent.com/assets/15528032/24201526/9374b990-0f10-11e7-9148-981219a02792.png)

**Comment by DanCarl857** [comment]
I am currently updating the models for this

**Comment by awasum** [comment]
I have already implemented this design. I am just waiting for Omeri to send me some information before sending the PR.

**Comment by DanCarl857** [comment]
What information?

**Comment by DanCarl857** [comment]
Because I need this to proceed
